const allData = {
          "forging": [
    {
        "Name": "Copper Bar",
        "Level": 1,
        "Base Time": "15 s",
        "Skill Exp": 1,
        "Vendor Price": "4 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 1,
        "Requirement 2": "Copper Ore",
        "Requirement 2 Amount": 2
    },
    {
        "Name": "Leather Handle",
        "Level": 1,
        "Base Time": "120 s",
        "Skill Exp": 9,
        "Vendor Price": "56 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 1,
        "Requirement 2": "Leather",
        "Requirement 2 Amount": 10,
        "Requirement 3": "Basic Solution",
        "Requirement 3 Amount": 2
    },
    {
        "Name": "Copper Bodyarmor",
        "Level": 1,
        "Base Time": "240 s",
        "Skill Exp": 18,
        "Vendor Price": "111 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 1,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 4,
        "Requirement 3": "Copper Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Copper Boots",
        "Level": 1,
        "Base Time": "240 s",
        "Skill Exp": 18,
        "Vendor Price": "111 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 1,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 4,
        "Requirement 3": "Copper Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Copper Gloves",
        "Level": 1,
        "Base Time": "240 s",
        "Skill Exp": 18,
        "Vendor Price": "111 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 1,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 4,
        "Requirement 3": "Copper Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Copper Helmet",
        "Level": 1,
        "Base Time": "240 s",
        "Skill Exp": 18,
        "Vendor Price": "111 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 1,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 4,
        "Requirement 3": "Copper Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Copper Sword",
        "Level": 1,
        "Base Time": "240 s",
        "Skill Exp": 18,
        "Vendor Price": "111 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 1,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 4,
        "Requirement 3": "Copper Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Copper Shield",
        "Level": 1,
        "Base Time": "240 s",
        "Skill Exp": 18,
        "Vendor Price": "111 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 1,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 4,
        "Requirement 3": "Copper Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Iron Bar",
        "Level": 10,
        "Base Time": "20 s",
        "Skill Exp": 2,
        "Vendor Price": "8 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 2,
        "Requirement 2": "Iron Ore",
        "Requirement 2 Amount": 2
    },
    {
        "Name": "Thick Leather Handle",
        "Level": 10,
        "Base Time": "160 s",
        "Skill Exp": 18,
        "Vendor Price": "56 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 2,
        "Requirement 2": "Thick Leather",
        "Requirement 2 Amount": 10,
        "Requirement 3": "Basic Solution",
        "Requirement 3 Amount": 4
    },
    {
        "Name": "Iron Bodyarmor",
        "Level": 10,
        "Base Time": "320 s",
        "Skill Exp": 36,
        "Vendor Price": "182 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 2,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 8,
        "Requirement 3": "Iron Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Iron Boots",
        "Level": 10,
        "Base Time": "320 s",
        "Skill Exp": 36,
        "Vendor Price": "182 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 2,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 8,
        "Requirement 3": "Iron Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Iron Gloves",
        "Level": 10,
        "Base Time": "320 s",
        "Skill Exp": 36,
        "Vendor Price": "182 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 2,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 8,
        "Requirement 3": "Iron Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Iron Helmet",
        "Level": 10,
        "Base Time": "320 s",
        "Skill Exp": 36,
        "Vendor Price": "182 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 2,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 8,
        "Requirement 3": "Iron Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Iron Sword",
        "Level": 10,
        "Base Time": "320 s",
        "Skill Exp": 36,
        "Vendor Price": "182 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 2,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 8,
        "Requirement 3": "Iron Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Thick Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Iron Shield",
        "Level": 10,
        "Base Time": "320 s",
        "Skill Exp": 36,
        "Vendor Price": "182 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 2,
        "Requirement 2": "Basic Flux",
        "Requirement 2 Amount": 8,
        "Requirement 3": "Iron Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Thick Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Silver Bar",
        "Level": 20,
        "Base Time": "30 s",
        "Skill Exp": 4,
        "Vendor Price": "15 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 3,
        "Requirement 2": "Silver Ore",
        "Requirement 2 Amount": 2,    
    },
    {
        "Name": "Sturdy Leather Handle",
        "Level": 20,
        "Base Time": "240 s",
        "Skill Exp": 36,
        "Vendor Price": "56 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 3,
        "Requirement 2": "Sturdy Leather",
        "Requirement 2 Amount": 10,
        "Requirement 3": "Quality Solution",
        "Requirement 3 Amount": 6
    },
    {
        "Name": "Silver Bodyarmor",
        "Level": 20,
        "Base Time": "480 s",
        "Skill Exp": 72,
        "Vendor Price": "287 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 3,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 12,
        "Requirement 3": "Silver Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Silver Boots",
        "Level": 20,
        "Base Time": "480 s",
        "Skill Exp": 72,
        "Vendor Price": "287 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 3,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 12,
        "Requirement 3": "Silver Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Silver Gloves",
        "Level": 20,
        "Base Time": "480 s",
        "Skill Exp": 72,
        "Vendor Price": "287 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 3,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 12,
        "Requirement 3": "Silver Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Silver Helmet",
        "Level": 20,
        "Base Time": "480 s",
        "Skill Exp": 72,
        "Vendor Price": "287 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 3,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 12,
        "Requirement 3": "Silver Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Silver Sword",
        "Level": 20,
        "Base Time": "480 s",
        "Skill Exp": 72,
        "Vendor Price": "287 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 3,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 12,
        "Requirement 3": "Silver Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Sturdy Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Silver Shield",
        "Level": 20,
        "Base Time": "480 s",
        "Skill Exp": 72,
        "Vendor Price": "287 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 3,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 12,
        "Requirement 3": "Silver Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Sturdy Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Gold Bar",
        "Level": 30,
        "Base Time": "40 s",
        "Skill Exp": 7,
        "Vendor Price": "34 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 4,
        "Requirement 2": "Gold Ore",
        "Requirement 2 Amount": 2,
    },
    {
        "Name": "Heavy Leather Handle",
        "Level": 30,
        "Base Time": "320 s",
        "Skill Exp": 63,
        "Vendor Price": "56 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 4,
        "Requirement 2": "Heavy Leather",
        "Requirement 2 Amount": 10,
        "Requirement 3": "Quality Solution",
        "Requirement 3 Amount": 8
    },
    {
        "Name": "Gold Bodyarmor",
        "Level": 30,
        "Base Time": "640 s",
        "Skill Exp": 126,
        "Vendor Price": "673 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 4,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 16,
        "Requirement 3": "Gold Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Gold Boots",
        "Level": 30,
        "Base Time": "640 s",
        "Skill Exp": 126,
        "Vendor Price": "673 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 4,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 16,
        "Requirement 3": "Gold Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Gold Gloves",
        "Level": 30,
        "Base Time": "640 s",
        "Skill Exp": 126,
        "Vendor Price": "673 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 4,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 16,
        "Requirement 3": "Gold Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Gold Helmet",
        "Level": 30,
        "Base Time": "640 s",
        "Skill Exp": 126,
        "Vendor Price": "673 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 4,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 16,
        "Requirement 3": "Gold Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Gold Sword",
        "Level": 30,
        "Base Time": "640 s",
        "Skill Exp": 126,
        "Vendor Price": "673 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 4,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 16,
        "Requirement 3": "Gold Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Heavy Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Gold Shield",
        "Level": 30,
        "Base Time": "640 s",
        "Skill Exp": 126,
         "Vendor Price": "673 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 4,
        "Requirement 2": "Quality Flux",
        "Requirement 2 Amount": 16,
        "Requirement 3": "Gold Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Heavy Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Platinum Bar",
        "Level": 40,
        "Base Time": "50 s",
        "Skill Exp": 11,
        "Vendor Price": "72 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 5,
        "Requirement 2": "Platinum Ore",
        "Requirement 2 Amount": 2,
    },
    {
        "Name": "Tough Leather Handle",
        "Level": 40,
        "Base Time": "400 s",
        "Skill Exp": 99,
        "Vendor Price": "56 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 5,
        "Requirement 2": "Tough Leather",
        "Requirement 2 Amount": 10,
        "Requirement 3": "Advanced Solution",
        "Requirement 3 Amount": 10
    },
    {
        "Name": "Platinum Bodyarmor",
        "Level": 40,
        "Base Time": "800 s",
        "Skill Exp": 188,
        "Vendor Price": "923 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 5,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 20,
        "Requirement 3": "Platinum Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Platinum Boots",
        "Level": 40,
        "Base Time": "800 s",
        "Skill Exp": 188,
        "Vendor Price": "923 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 5,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 20,
        "Requirement 3": "Platinum Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Platinum Gloves",
        "Level": 40,
        "Base Time": "800 s",
        "Skill Exp": 188,
        "Vendor Price": "923 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 5,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 20,
        "Requirement 3": "Platinum Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Platinum Helmet",
        "Level": 40,
        "Base Time": "800 s",
        "Skill Exp": 188,
        "Vendor Price": "923 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 5,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 20,
        "Requirement 3": "Platinum Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Platinum Sword",
        "Level": 40,
        "Base Time": "800 s",
        "Skill Exp": 188,
        "Vendor Price": "923 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 5,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 20,
        "Requirement 3": "Platinum Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Tough Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Platinum Shield",
        "Level": 40,
        "Base Time": "800 s",
        "Skill Exp": 188,
        "Vendor Price": "923 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 5,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 20,
        "Requirement 3": "Platinum Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Tough Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Mithril Bar",
        "Level": 50,
        "Base Time": "60 s",
        "Skill Exp": 16,
        "Vendor Price": "120 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 6,
        "Requirement 2": "Mithril Ore",
        "Requirement 2 Amount": 2,
    },
    {
        "Name": "Reinforced Leather Handle",
        "Level": 50,
        "Base Time": "120 s",
        "Skill Exp": 144,
        "Vendor Price": "56 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 6,
        "Requirement 2": "Reinforced Leather",
        "Requirement 2 Amount": 10,
        "Requirement 3": "Advanced Solution",
        "Requirement 3 Amount": 10
    },
    {
        "Name": "Mithril Bodyarmor",
        "Level": 50,
        "Base Time": "1120 s",
        "Skill Exp": 288,
        "Vendor Price": "1347 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 6,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 24,
        "Requirement 3": "Mithril Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Mithril Boots",
        "Level": 50,
        "Base Time": "1120 s",
        "Skill Exp": 288,
        "Vendor Price": "1347 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 6,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 24,
        "Requirement 3": "Mithril Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Mithril Gloves",
        "Level": 50,
        "Base Time": "1120 s",
        "Skill Exp": 288,
        "Vendor Price": "1347 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 6,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 24,
        "Requirement 3": "Mithril Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Mithril Helmet",
        "Level": 50,
        "Base Time": "1120 s",
        "Skill Exp": 288,
        "Vendor Price": "1347 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 6,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 24,
        "Requirement 3": "Palladium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Mithril Sword",
        "Level": 50,
        "Base Time": "1120 s",
        "Skill Exp": 288,
        "Vendor Price": "1347 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 6,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 24,
        "Requirement 3": "Mithril Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Reinforced Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Mithril Shield",
        "Level": 50,
        "Base Time": "1120 s",
        "Skill Exp": 288,
        "Vendor Price": "1347 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 6,
        "Requirement 2": "Advanced Flux",
        "Requirement 2 Amount": 24,
        "Requirement 3": "Mithril Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Reinforced Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Adamantite Bar",
        "Level": 60,
        "Base Time": "70 s",
        "Skill Exp": 22,
        "Vendor Price": "207 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 7,
        "Requirement 2": "Adamantite Ore",
        "Requirement 2 Amount": 2
    },
    {
        "Name": "Shadowhide Leather Handle",
        "Level": 60,
        "Base Time": "120 s",
        "Skill Exp": 198,
        "Vendor Price": "56 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 7,
        "Requirement 2": "Shadowhide Leather",
        "Requirement 2 Amount": 10,
        "Requirement 3": "Exotic Solution",
        "Requirement 3 Amount": 14
    },
    {
        "Name": "Adamantite Bodyarmor",
        "Level": 60,
        "Base Time": "1120 s",
        "Skill Exp": 396,
        "Vendor Price": "2087 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 7,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 28,
        "Requirement 3": "Adamantite Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Adamantite Boots",
        "Level": 60,
        "Base Time": "1120 s",
        "Skill Exp": 396,
        "Vendor Price": "2087 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 7,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 28,
        "Requirement 3": "Adamantite Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Adamantite Gloves",
        "Level": 60,
        "Base Time": "1120 s",
        "Skill Exp": 396,
        "Vendor Price": "2087 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 7,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 28,
        "Requirement 3": "Adamantite Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Adamantite Helmet",
        "Level": 60,
        "Base Time": "1120 s",
        "Skill Exp": 396,
        "Vendor Price": "2087 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 7,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 28,
        "Requirement 3": "Adamantite Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Adamantite Sword",
        "Level": 60,
        "Base Time": "1120 s",
        "Skill Exp": 396,
        "Vendor Price": "2087 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 7,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 28,
        "Requirement 3": "Adamantite Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Shadowhide Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Adamantite Shield",
        "Level": 60,
        "Base Time": "1120 s",
        "Skill Exp": 396,
        "Vendor Price": "2087 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 7,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 28,
        "Requirement 3": "Adamantite Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Shadowhide Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Eternium Bar",
        "Level": 70,
        "Base Time": "80 s",
        "Skill Exp": 29,
        "Vendor Price": "95 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 8,
        "Requirement 2": "Eternium Ore",
        "Requirement 2 Amount": 2
    },
    {
        "Name": "Dragonhide Leather Handle",
        "Level": 70,
        "Base Time": "640 s",
        "Skill Exp": 261,
        "Vendor Price": "1347 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 8,
        "Requirement 2": "Exotic Solution",
        "Requirement 2 Amount": 16,
        "Requirement 3": "Dragonhide Leather",
        "Requirement 3 Amount": 10
    },
    {
        "Name": "Eternium Bodyarmor",
        "Level": 70,
        "Base Time": "1280 s",
        "Skill Exp": 522,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 8,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 32,
        "Requirement 3": "Eternium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Eternium Boots",
        "Level": 70,
        "Base Time": "1280 s",
        "Skill Exp": 522,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 8,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 32,
        "Requirement 3": "Eternium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Eternium Gloves",
        "Level": 70,
        "Base Time": "1280 s",
        "Skill Exp": 522,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 8,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 32,
        "Requirement 3": "Eternium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Eternium Helmet",
        "Level": 70,
        "Base Time": "1280 s",
        "Skill Exp": 522,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 8,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 32,
        "Requirement 3": "Eternium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Eternium Sword",
        "Level": 70,
        "Base Time": "1280 s",
        "Skill Exp": 522,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 8,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 32,
        "Requirement 3": "Eternium Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Dragonhide Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Eternium Shield",
        "Level": 70,
        "Base Time": "1280 s",
        "Skill Exp": 522,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 8,
        "Requirement 2": "Exotic Flux",
        "Requirement 2 Amount": 32,
        "Requirement 3": "Eternium Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Dragonhide Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Nyxium Bar",
        "Level": 80,
        "Base Time": "90 s",
        "Skill Exp": 37,
        "Vendor Price": "95 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 9,
        "Requirement 2": "Nyxium Ore",
        "Requirement 2 Amount": 2
    },
    {
        "Name": "Abyssal Leather Handle",
        "Level": 80,
        "Base Time": "720 s",
        "Skill Exp": 333,
        "Vendor Price": "1347 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 9,
        "Requirement 2": "Premium Solution",
        "Requirement 2 Amount": 18,
        "Requirement 3": "Abyssal Leather",
        "Requirement 3 Amount": 10
    },
    {
        "Name": "Nyxium Bodyarmor",
        "Level": 80,
        "Base Time": "1440 s",
        "Skill Exp": 667,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 9,
        "Requirement 2": "Premium Flux",
        "Requirement 2 Amount": 36,
        "Requirement 3": "Nyxium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Nyxium Boots",
        "Level": 80,
        "Base Time": "1440 s",
        "Skill Exp": 667,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 9,
        "Requirement 2": "Premium Flux",
        "Requirement 2 Amount": 36,
        "Requirement 3": "Nyxium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Nyxium Gloves",
        "Level": 80,
        "Base Time": "1440 s",
        "Skill Exp": 667,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 9,
        "Requirement 2": "Premium Flux",
        "Requirement 2 Amount": 36,
        "Requirement 3": "Nyxium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Nyxium Helmet",
        "Level": 80,
        "Base Time": "1440 s",
        "Skill Exp": 667,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 9,
        "Requirement 2": "Premium Flux",
        "Requirement 2 Amount": 36,
        "Requirement 3": "Nyxium Bar",
        "Requirement 3 Amount": 20
    },
    {
        "Name": "Nyxium Sword",
        "Level": 80,
        "Base Time": "1440 s",
        "Skill Exp": 667,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 9,
        "Requirement 2": "Premium Flux",
        "Requirement 2 Amount": 36,
        "Requirement 3": "Nyxium Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Abyssal Leather Handle",
        "Requirement 4 Amount": 1
    },
    {
        "Name": "Nyxium Shield",
        "Level": 80,
        "Base Time": "1440 s",
        "Skill Exp": 667,
        "Vendor Price": "2686 ouros",
        "Requirement 1": "Coal Ore",
        "Requirement 1 Amount": 9,
        "Requirement 2": "Premium Flux",
        "Requirement 2 Amount": 36,
        "Requirement 3": "Nyxium Bar",
        "Requirement 3 Amount": 20,
        "Requirement 4": "Abyssal Leather Handle",
        "Requirement 4 Amount": 1
    }
],
        "leatherworking": [
{
                "Name": "Leather",
                "Level": 1,
                "Base Time": "15 s",
                "Skill Exp": 1,
                "Vendor Price": "4 ouros",
                "Requirement 1": "Leather Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 1
            },
            {
                "Name": "Wool Bowstring",
                "Level": 1,
                "Base Time": "120 s",
                "Skill Exp": 9,
                "Vendor Price": "56 ouros",
                "Requirement 1": "Wool Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Thread",
                "Requirement 3 Amount": 2
            },
            {
                "Name": "Leather Bodyarmor",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Leather Boots",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Leather Gloves",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Leather Hat",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Leather Bow",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 4,
                "Requirement 4": "Wool Bowstring",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Thick Leather",
                "Level": 10,
                "Base Time": "20 s",
                "Skill Exp": 2,
                "Vendor Price": "8 ouros",
                "Requirement 1": "Thick Leather Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 2
            },
            {
                "Name": "Silk Bowstring",
                "Level": 10,
                "Base Time": "160 s",
                "Skill Exp": 18,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Silk Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Basic Thread",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Thick Leather Bodyarmor",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Thick Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Thick Leather Boots",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Thick Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Thick Leather Gloves",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Thick Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Thick Leather Hat",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Thick Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Thick Leather Bow",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Thick Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Basic Solution",
                "Requirement 3 Amount": 8,
                "Requirement 4": "Silk Bowstring",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Sturdy Leather",
                "Level": 20,
                "Base Time": "30 s",
                "Skill Exp": 4,
                "Vendor Price": "15 ouros",
                "Requirement 1": "Sturdy Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 3,
            },
            {
                "Name": "Moonlit Bowstring",
                "Level": 20,
                "Base Time": "240 s",
                "Skill Exp": 36,
                "Vendor Price": "56 ouros",
                "Requirement 1": "Moonlit Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 6
            },
            {
                "Name": "Sturdy Leather Bodyarmor",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Sturdy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Sturdy Leather Boots",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Sturdy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Sturdy Leather Gloves",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Sturdy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Sturdy Leather Hat",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Sturdy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Sturdy Leather Bow",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Sturdy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 12,
                "Requirement 4": "Moonlit Bowstring",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Heavy Leather",
                "Level": 30,
                "Base Time": "40 s",
                "Skill Exp": 7,
                "Vendor Price": "34 ouros",
                "Requirement 1": "Heavy Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 4,
            },
            {
                "Name": "Etheric Bowstring",
                "Level": 30,
                "Base Time": "320 s",
                "Skill Exp": 63,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Etheric Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 8,
            },
            {
                "Name": "Heavy Leather Bodyarmor",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Heavy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Heavy Leather Boots",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Heavy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Heavy Leather Gloves",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Heavy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Heavy Leather Hat",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Heavy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Heavy Leather Bow",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Heavy Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Solution",
                "Requirement 3 Amount": 16,
                "Requirement 4": "Etheric Bowstring",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Tough Leather",
                "Level": 40,
                "Base Time": "50 s",
                "Skill Exp": 11,
                "Vendor Price": "72 ouros",
                "Requirement 1": "Tough Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 5,
            },
            {
                "Name": "Shadow Bowstring",
                "Level": 40,
                "Base Time": "400 s",
                "Skill Exp": 99,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Shadow Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 10
            },
            {
                "Name": "Tough Leather Bodyarmor",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Tough Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 20
            },
            {
                "Name": "Tough Leather Boots",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Tough Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 2
            },
            {
                "Name": "Tough Leather Gloves",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Tough Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 2
            },
            {
                "Name": "Tough Leather Hat",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Tough Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 2
            },
            {
                "Name": "Tough Leather Bow",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Tough Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 20,
                "Requirement 4": "Shadow Bowstring",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Reinforced Leather",
                "Level": 50,
                "Base Time": "60 s",
                "Skill Exp": 16,
                "Vendor Price": "120 ouros",
                "Requirement 1": "Reindorced Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 6,
            },
            {
                "Name": "Mystweave Bowstring",
                "Level": 50,
                "Base Time": "480 s",
                "Skill Exp": 144,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Mystweave Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Reinforced Leather Bodyarmor",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Reinforced Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 24
            },
            {
                "Name": "Reinforced Leather Boots",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Reinforced Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 24
            },
            {
                "Name": "Reinforced Leather Gloves",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Reinforced Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 24
            },
            {
                "Name": "Reinforced Leather Hat",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Reinforced Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 24
            },
            {
                "Name": "Reinforced Leather Bow",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Reinforced Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Solution",
                "Requirement 3 Amount": 24,
                "Requirement 4": "Mystweave Bowstring",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Shadowhide Leather",
                "Level": 60,
                "Base Time": "70 s",
                "Skill Exp": 22,
                "Vendor Price": "207 ouros",
                "Requirement 1": "Shadowhide Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 7,
            },
            {
                "Name": "Arcane Bowstring",
                "Level": 60,
                "Base Time": "560 s",
                "Skill Exp": 198,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Aether Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 14
            },
            {
                "Name": "Shadowhide Leather Bodyarmor",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Shadowhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 28
            },
            {
                "Name": "Shadowhide Leather Boots",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Shadowhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 28
            },
            {
                "Name": "Shadowhide Leather Gloves",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Shadowhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 28
            },
            {
                "Name": "Shadowhide Leather Hat",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Shadowhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 28
            },
            {
                "Name": "Shadowhide Leather Bow",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Shadowhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 28,
                "Requirement 4": "Arcane Bowstring",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Dragonhide Leather",
                "Level": 70,
                "Base Time": "80 s",
                "Skill Exp": 29,
                "Vendor Price": "95 ouros",
                "Requirement 1": "Dragonhide Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 8,
            },
            {
                "Name": "Aether Bowstring",
                "Level": 70,
                "Base Time": "640 s",
                "Skill Exp": 261,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Aether Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Dragonhide Leather Bodyarmor",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Dragonhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Dragonhide Leather Boots",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Dragonhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Dragonhide Leather Gloves",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Dragonhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Dragonhide Leather Hat",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Dragonhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Dragonhide Leather Bow",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Dragonhide Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Solution",
                "Requirement 3 Amount": 32,
                "Requirement 4": "Aether Bowstring",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Abyssal Leather",
                "Level": 80,
                "Base Time": "90 s",
                "Skill Exp": 37,
                "Vendor Price": "95 ouros",
                "Requirement 1": "Abyssal Hide",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 9,
            },
            {
                "Name": "Astral Bowstring",
                "Level": 80,
                "Base Time": "720 s",
                "Skill Exp": 333,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Astral Cloth",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Thread",
                "Requirement 3 Amount": 18
            },
            {
                "Name": "Abyssal Leather Bodyarmor",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Abyssal Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Solution",
                "Requirement 3 Amount": 36
            },
            {
                "Name": "Abyssal Leather Boots",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Abyssal Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Solution",
                "Requirement 3 Amount": 36
            },
            {
                "Name": "Abyssal Leather Gloves",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Abyssal Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Solution",
                "Requirement 3 Amount": 36
            },
            {
                "Name": "Dragonhide Leather Hat",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Abyssal Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Solution",
                "Requirement 3 Amount": 36
            },
            {
                "Name": "Abyssal Leather Bow",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Abyssal Leather",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Bone Charcoal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Solution",
                "Requirement 3 Amount": 36,
                "Requirement 4": "Astral Bowstring",
                "Requirement 4 Amount": 1
            }
        ],
            "tailoring": [
            {
                "Name": "Wool Cloth",
                "Level": 1,
                "Base Time": "15 s",
                "Skill Exp": 1,
                "Vendor Price": "4 ouros",
                "Requirement 1": "Raw Wool",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 1
            },
            {
                "Name": "Copper Gemstone",
                "Level": 1,
                "Base Time": "120 s",
                "Skill Exp": 9,
                "Vendor Price": "56 ouros",
                "Requirement 1": "Copper Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Flux",
                "Requirement 3 Amount": 2
            },
            {
                "Name": "Wool Gloves",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Wool Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Thread",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Wool Hat",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Wool Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Thread",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Wool Robe",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Wool Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Thread",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Wool Shoes",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Wool Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Thread",
                "Requirement 3 Amount": 4
            },
            {
                "Name": "Wool Staff",
                "Level": 1,
                "Base Time": "240 s",
                "Skill Exp": 18,
                "Vendor Price": "111 ouros",
                "Requirement 1": "Wool Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 1,
                "Requirement 3": "Basic Thread",
                "Requirement 3 Amount": 4,
                "Requirement 4": "Copper Gemstone",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Silk Cloth",
                "Level": 10,
                "Base Time": "20 s",
                "Skill Exp": 2,
                "Vendor Price": "8 ouros",
                "Requirement 1": "Silkwisp",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 2
            },
            {
                "Name": "Iron Gemstone",
                "Level": 10,
                "Base Time": "160 s",
                "Skill Exp": 18,
                "Vendor Price": "112 ouros",
                "Requirement 1": "Iron Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Basic Flux",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Silk Gloves",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Silk Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Common Thread",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Silk Hat",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Silk Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Common Thread",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Silk Robe",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Silk Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Common Thread",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Silk Shoes",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Silk Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Common Thread",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Silk Staff",
                "Level": 10,
                "Base Time": "320 s",
                "Skill Exp": 36,
                "Vendor Price": "182 ouros",
                "Requirement 1": "Silk Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 2,
                "Requirement 3": "Common Thread",
                "Requirement 3 Amount": 8,
                "Requirement 4": "Iron Gemstone",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Moonlit Cloth",
                "Level": 20,
                "Base Time": "30 s",
                "Skill Exp": 4,
                "Vendor Price": "15 ouros",
                "Requirement 1": "Moonglow",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 3,
            },
            {
                "Name": "Silver Gemstone",
                "Level": 20,
                "Base Time": "240 s",
                "Skill Exp": 36,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Steel Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Flux",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Moonlit Gloves",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Moonlit Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Moonlit Hat",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Moonlit Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Moonlit Robe",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Moonlit Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Moonlit Shoes",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Moonlit Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Moonlit Staff",
                "Level": 20,
                "Base Time": "480 s",
                "Skill Exp": 72,
                "Vendor Price": "287 ouros",
                "Requirement 1": "Moonlit Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 3,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 12,
                "Requirement 4": "Silver Gemstone",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Etheric Cloth",
                "Level": 30,
                "Base Time": "40 s",
                "Skill Exp": 7,
                "Vendor Price": "34 ouros",
                "Requirement 1": "Etherbloom",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 4,
            },
            {
                "Name": "Gold Gemstone",
                "Level": 30,
                "Base Time": "320 s",
                "Skill Exp": 63,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Gold Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Flux",
                "Requirement 3 Amount": 8
            },
            {
                "Name": "Etheric Gloves",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Etheric Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Etheric Hat",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Etheric Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Etheric Robe",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Etheric Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Etheric Shoes",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Etheric Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 16
            },
            {
                "Name": "Etheric Staff",
                "Level": 30,
                "Base Time": "640 s",
                "Skill Exp": 126,
                "Vendor Price": "673 ouros",
                "Requirement 1": "Etheric Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 4,
                "Requirement 3": "Quality Thread",
                "Requirement 3 Amount": 16,
                "Requirement 4": "Gold Gemstone",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Shadow Cloth",
                "Level": 40,
                "Base Time": "50 s",
                "Skill Exp": 11,
                "Vendor Price": "72 ouros",
                "Requirement 1": "Shadowvine",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 5,
            },
            {
                "Name": "Platinum Gemstone",
                "Level": 40,
                "Base Time": "400 s",
                "Skill Exp": 99,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Platinum Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Flux",
                "Requirement 3 Amount": 10
            },
            {
                "Name": "Shadow Gloves",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Shadow Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 20
            },
            {
                "Name": "Shadow Hat",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Shadow Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 20
            },
            {
                "Name": "Shadow Robe",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Shadow Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 20
            },
            {
                "Name": "Shadow Shoes",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Shadow Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 20
            },
            {
                "Name": "Shadow Staff",
                "Level": 40,
                "Base Time": "800 s",
                "Skill Exp": 198,
                "Vendor Price": "923 ouros",
                "Requirement 1": "Shadow Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 5,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 20,
                "Requirement 4": "Platinum Gemstone",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Mystweave Cloth",
                "Level": 50,
                "Base Time": "60 s",
                "Skill Exp": 16,
                "Vendor Price": "120 ouros",
                "Requirement 1": "Mystroot",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 6,
            },
            {
                "Name": "Mithril Gemstone",
                "Level": 50,
                "Base Time": "480 s",
                "Skill Exp": 2144,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Mithril Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Flux",
                "Requirement 3 Amount": 12
            },
            {
                "Name": "Mystic Gloves",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Mystweave Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 24
            },
            {
                "Name": "Mystic Hat",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Mystweave Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 24
            },
            {
                "Name": "Mystic Robe",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Mystweave Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 24
            },
            {
                "Name": "Mystic Shoes",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Mystweave Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 24
            },
            {
                "Name": "Mystic Staff",
                "Level": 50,
                "Base Time": "960 s",
                "Skill Exp": 288,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Mystweave Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 6,
                "Requirement 3": "Advanced Thread",
                "Requirement 3 Amount": 24,
                "Requirement 4": "Mithril Gemstone",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Arcane Cloth",
                "Level": 60,
                "Base Time": "70 s",
                "Skill Exp": 22,
                "Vendor Price": "1047 ouros",
                "Requirement 1": "Arcanleaf",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 7,
            },
            {
                "Name": "Adamantite Gemstone",
                "Level": 60,
                "Base Time": "560 s",
                "Skill Exp": 198,
                "Vendor Price": "73 ouros",
                "Requirement 1": "Adamantite Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Flux",
                "Requirement 3 Amount": 14
            },
            {
                "Name": "Arcane Gloves",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Arcane Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 28
            },
            {
                "Name": "Arcane Hat",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Arcane Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 28
            },
            {
                "Name": "Arcane Robe",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Arcane Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 28
            },
            {
                "Name": "Arcane Shoes",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Arcane Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 28
            },
            {
                "Name": "Arcane Staff",
                "Level": 60,
                "Base Time": "1120 s",
                "Skill Exp": 396,
                "Vendor Price": "2087 ouros",
                "Requirement 1": "Arcane Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 7,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 28,
                "Requirement 4": "Adamantite Gemstone",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Aether Cloth",
                "Level": 70,
                "Base Time": "80 s",
                "Skill Exp": 29,
                "Vendor Price": "95 ouros",
                "Requirement 1": "Aetherbloom",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 8,
            },
            {
                "Name": "Eternium Gemstone",
                "Level": 70,
                "Base Time": "640 s",
                "Skill Exp": 261,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Eternium Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Flux",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Aether Gloves",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Aether Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Aether Hat",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Aether Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Aether Robe",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Aether Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Aether Shoes",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Aether Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 32
            },
            {
                "Name": "Aether Staff",
                "Level": 70,
                "Base Time": "1280 s",
                "Skill Exp": 522,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Aether Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 8,
                "Requirement 3": "Exotic Thread",
                "Requirement 3 Amount": 32,
                "Requirement 4": "Eternium Gemstone",
                "Requirement 4 Amount": 1
            },
            {
                "Name": "Astral Cloth",
                "Level": 80,
                "Base Time": "90 s",
                "Skill Exp": 37,
                "Vendor Price": "95 ouros",
                "Requirement 1": "Astralis",
                "Requirement 1 Amount": 2,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 9,
            },
            {
                "Name": "Nyxium Gemstone",
                "Level": 80,
                "Base Time": "720 s",
                "Skill Exp": 33,
                "Vendor Price": "1347 ouros",
                "Requirement 1": "Nyxium Bar",
                "Requirement 1 Amount": 10,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Flux",
                "Requirement 3 Amount": 18
            },
            {
                "Name": "Astral Gloves",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Astral Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Thread",
                "Requirement 3 Amount": 36
            },
            {
                "Name": "Astral Hat",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Astral Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Thread",
                "Requirement 3 Amount": 36
            },
            {
                "Name": "Astral Robe",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Astral Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Thread",
                "Requirement 3 Amount": 36
            },
            {
                "Name": "Astral Shoes",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Astral Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Thread",
                "Requirement 3 Amount": 36
            },
            {
                "Name": "Astral Staff",
                "Level": 80,
                "Base Time": "1440 s",
                "Skill Exp": 667,
                "Vendor Price": "2686 ouros",
                "Requirement 1": "Astral Cloth",
                "Requirement 1 Amount": 20,
                "Requirement 2": "Arcane Crystal",
                "Requirement 2 Amount": 9,
                "Requirement 3": "Premium Thread",
                "Requirement 3 Amount": 36,
                "Requirement 4": "Nyxium Gemstone",
                "Requirement 4 Amount": 1
            }
        ]
        };